export const GET_PRODUCT_ID_SUCCESS = 'GET_PRODUCT_ID_SUCCESS';
export const GET_PRODUCT_ID__FAIL = 'GET_PRODUCT_ID__FAIL';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const GET_ALL_PRODUCT_FAIL = 'GET_ALL_PRODUCT_FAIL';